function pump_poly = pump_poly(u)
%PUMP_POLY
%    PUMP_POLY = PUMP_POLY(U)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    22-Dec-2025 22:40:42

pump_poly = u.*(-9.955703104845354e+3)+u.^2.*2.032545853650735e+4-u.^3.*1.739284801980545e+4+u.^4.*5.421798347330023e+3+1.744858576463777e+3;
end
